### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by impeeza** [zqb-all/convertfb#1]
Hi, first at all thanks for your work.

Fiddling with the script discover you need Python2, but is now almost deprecated.

The attached file works fine on Python 3, the real only change is the print function, on Python 3 require parentheses.

and now the python-imaging module is called Pillow
 
[convertfb3.zip](https://github.com/zqb-all/convertfb/files/10042784/convertfb3.zip)

regards from Colombia.

**Comment by btc08gh** [comment]
Extremely helpful.  I tested this myself and it works great!

**Comment by impeeza** [comment]
created pullrequest https://github.com/zqb-all/convertfb/pull/2
